layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  limit: 12
  exclude:
    forks: true
    projects:
    - personal-website
    - slack-clone

social_media:
  linkedin: marcioporto
  # stackoverflow: your_user_id
  # twitter: your_username

topics:
  - name: Deep Learning
  - name: Deep Reinforcement Learning
  - name: Tensorflow
